COMPONENT=testtkn_cfg

CFLAGS += -I$(TINYOS_OS_DIR)/lib/printf

CFLAGS += -I$(TINYOS_OS_DIR)/lib/mac/tkn154
CFLAGS += -DIEEE154_BEACON_TX_DISABLED

include $(TINYOS_ROOT_DIR)/Makefile.include
include $(TINYOS_OS_DIR)/lib/mac/tkn154/Makefile.include

